# get products
GET http://localhost:3000/products

# get products by id 
GET http://localhost:3000/products/5d5c77be-409f-11ef-a232-0f1438dba299

# create a product
#POST http://localhost:3000/products
#{
#    name: "camisa",
#    price: "10",
#}

# delete a product
#DELETE http://localhost:3000/products

# update a product
#PATCH http://localhost:3000/products
